services:
  postgres:
    image: postgres:16-alpine
    container_name: gameshub
    environment:
      POSTGRES_DB: gameshub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always